/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IHana
 */
public class standardcalculator extends javax.swing.JFrame {
    String angka;
    double jumlah,angka1, angka2;
    int pilih;
    
    public standardcalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        display = new javax.swing.JTextField();
        tblbagi = new javax.swing.JButton();
        tblhasil = new javax.swing.JButton();
        tblclear = new javax.swing.JButton();
        tblkurang = new javax.swing.JButton();
        tblkali = new javax.swing.JButton();
        tbltambah = new javax.swing.JButton();
        tbl7 = new javax.swing.JButton();
        tbl8 = new javax.swing.JButton();
        tbl9 = new javax.swing.JButton();
        tbl4 = new javax.swing.JButton();
        tbl5 = new javax.swing.JButton();
        tbl6 = new javax.swing.JButton();
        tbl1 = new javax.swing.JButton();
        tbl2 = new javax.swing.JButton();
        tblkoma = new javax.swing.JButton();
        tbl0 = new javax.swing.JButton();
        tbl3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tblpersen = new javax.swing.JButton();
        tblakar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desktop Kalkulator");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setEditable(false);
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 50));

        tblbagi.setText("/");
        tblbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblbagiActionPerformed(evt);
            }
        });
        getContentPane().add(tblbagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 60, 40));

        tblhasil.setText("=");
        tblhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblhasilActionPerformed(evt);
            }
        });
        getContentPane().add(tblhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 60, 40));

        tblclear.setText("c");
        tblclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblclearActionPerformed(evt);
            }
        });
        getContentPane().add(tblclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 40));

        tblkurang.setText("-");
        tblkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkurangActionPerformed(evt);
            }
        });
        getContentPane().add(tblkurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 60, 40));

        tblkali.setText("x");
        tblkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkaliActionPerformed(evt);
            }
        });
        getContentPane().add(tblkali, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 60, 40));

        tbltambah.setText("+");
        tbltambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbltambahActionPerformed(evt);
            }
        });
        getContentPane().add(tbltambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 60, 40));

        tbl7.setText("7");
        tbl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl7ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 40));

        tbl8.setText("8");
        tbl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl8ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 40));

        tbl9.setText("9");
        tbl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl9ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, 40));

        tbl4.setText("4");
        tbl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl4ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 40));

        tbl5.setText("5");
        tbl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl5ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 90, 40));

        tbl6.setText("6");
        tbl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl6ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 90, 40));

        tbl1.setText("1");
        tbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 40));

        tbl2.setText("2");
        tbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl2ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 90, 40));

        tblkoma.setText(",");
        tblkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkomaActionPerformed(evt);
            }
        });
        getContentPane().add(tblkoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 90, 40));

        tbl0.setText("0");
        tbl0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl0ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 40));

        tbl3.setText("3");
        tbl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl3ActionPerformed(evt);
            }
        });
        getContentPane().add(tbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 90, 40));

        jLabel1.setText("Standard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        tblpersen.setText("%");
        tblpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblpersenActionPerformed(evt);
            }
        });
        getContentPane().add(tblpersen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, 40));

        tblakar.setText("√ ");
        tblakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblakarActionPerformed(evt);
            }
        });
        getContentPane().add(tblakar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkurangActionPerformed
        angka1 = Double.parseDouble(angka);
        display.setText("-");
        angka = "";
        pilih = 2;
    }//GEN-LAST:event_tblkurangActionPerformed

    private void tblbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblbagiActionPerformed
        angka1 = Double.parseDouble(angka);
        display.setText("/");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_tblbagiActionPerformed

    private void tbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl2ActionPerformed
        angka += "2";
        display.setText(angka);
    }//GEN-LAST:event_tbl2ActionPerformed

    private void tblclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblclearActionPerformed
        display.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        jumlah = 0.0;
        angka  = "";
    }//GEN-LAST:event_tblclearActionPerformed

    private void tbl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl7ActionPerformed
        angka += "7";
        display.setText(angka);
    }//GEN-LAST:event_tbl7ActionPerformed

    private void tbl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl8ActionPerformed
        angka += "8";
        display.setText(angka);
    }//GEN-LAST:event_tbl8ActionPerformed

    private void tbl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl9ActionPerformed
        angka += "9";
        display.setText(angka);
    }//GEN-LAST:event_tbl9ActionPerformed

    private void tbl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl4ActionPerformed
        angka += "4";
        display.setText(angka);
    }//GEN-LAST:event_tbl4ActionPerformed

    private void tbl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl5ActionPerformed
        angka += "5";
        display.setText(angka);
    }//GEN-LAST:event_tbl5ActionPerformed

    private void tbl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl6ActionPerformed
        angka += "6";
        display.setText(angka);
    }//GEN-LAST:event_tbl6ActionPerformed

    private void tbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl1ActionPerformed
        angka += "1";
        display.setText(angka);
    }//GEN-LAST:event_tbl1ActionPerformed

    private void tbl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl3ActionPerformed
        angka += "3";
        display.setText(angka);
    }//GEN-LAST:event_tbl3ActionPerformed

    private void tbl0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl0ActionPerformed
        angka += "0";
        display.setText(angka);
    }//GEN-LAST:event_tbl0ActionPerformed

    private void tblkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkomaActionPerformed
        angka += ".";
        display.setText(angka);
    }//GEN-LAST:event_tblkomaActionPerformed

    private void tbltambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbltambahActionPerformed
        angka1 = Double.parseDouble(angka);
        display.setText("+");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_tbltambahActionPerformed

    private void tblkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkaliActionPerformed
        angka1 = Double.parseDouble(angka);
        display.setText("*");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_tblkaliActionPerformed

    private void tblhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblhasilActionPerformed
        switch (pilih) {
            case 1 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 + angka2;
                angka  = Double.toString(jumlah);
                display.setText(angka);
                break;
            case 2 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 - angka2;
                angka  = Double.toString(jumlah);
                display.setText(angka);
                break;
            case 3 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 * angka2;
                angka  = Double.toString(jumlah);
                display.setText(angka);
                break;
            case 4 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 / angka2;
                angka  = Double.toString(jumlah);
                display.setText(angka);
                break;
            case 5 :
                jumlah = angka1/100;
                angka = Double.toString(jumlah);
                display.setText(angka);      
                break;
            case 6 :
                jumlah = Math.sqrt(angka1);
                angka = Double.toString(jumlah);
                display.setText(angka);
            default :
                break;
            
        }
    }//GEN-LAST:event_tblhasilActionPerformed

    private void tblpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblpersenActionPerformed
       angka1=Double.parseDouble(angka);
        display.setText("%");
        angka="";
        pilih=5;
    }//GEN-LAST:event_tblpersenActionPerformed

    private void tblakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblakarActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("√");
        angka="";
        pilih=6;
    }//GEN-LAST:event_tblakarActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(standardcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(standardcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(standardcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(standardcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new standardcalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tbl0;
    private javax.swing.JButton tbl1;
    private javax.swing.JButton tbl2;
    private javax.swing.JButton tbl3;
    private javax.swing.JButton tbl4;
    private javax.swing.JButton tbl5;
    private javax.swing.JButton tbl6;
    private javax.swing.JButton tbl7;
    private javax.swing.JButton tbl8;
    private javax.swing.JButton tbl9;
    private javax.swing.JButton tblakar;
    private javax.swing.JButton tblbagi;
    private javax.swing.JButton tblclear;
    private javax.swing.JButton tblhasil;
    private javax.swing.JButton tblkali;
    private javax.swing.JButton tblkoma;
    private javax.swing.JButton tblkurang;
    private javax.swing.JButton tblpersen;
    private javax.swing.JButton tbltambah;
    // End of variables declaration//GEN-END:variables
}
